### ISSUE TITLE
config.toml not fully implemented?

### ISSUE THREAD

**Issue by anthonymoon** [IceDBorn/IceDOS#133]
It appears the current commit is still referring the now defunct .nix file.

As the mount errors do not go away until. nix is re-added and modified.

**Comment by IceDBorn** [comment]
Can you better describe the problem? Also, did not know that other users were using my config lol. I'm open to PRs too btw.

**Comment by anthonymoon** [comment]
Hold on... it may be an issue on my side, my system config is setup as a flake.

I patched things up by adding my filesystems to the hardware-configuration.nix as expected, now things are cooking.

Hope you don't mind me trying out your config... thought that was the whole point of NixOS? Share the wealth?

I'm two days into Nix and I'm just trying to get my computer back together so I can play Steam games :)

Anyhow, it seems to be working now... but I'm sure something is going to explode any minute... so tired :/

**Comment by IceDBorn** [comment]
> Hold on... it may be an issue on my side, my system config is setup as a flake.

Are you using my config as a flake input? I'm not even sure if that works, to be honest.

> Hope you don't mind me trying out your config... thought that was the whole point of NixOS? Share the wealth?

I did not mean to be rude, I love that I can help you with my config. It is the whole purpose of this project in the first place.

> I'm two days into Nix and I'm just trying to get my computer back together so I can play Steam games :)

I feel for you...

> Anyhow, it seems to be working now... but I'm sure something is going to explode any minute... so tired :/

I want to add documentation to the wiki section of the project. Hopefully, it'll minimize errors produced by new users.
